var helper = require('../helper')
var assert = require('assert');

describe('Generated', function() {
  describe('isGenerated()', function() {
    it('should detect when files are generated', function() {
      // Generated .NET Docfiles
      assert.ok(helper.isGenerated("XML/net_docfile.xml"))
      // Long line
      assert.ok(!helper.isGenerated("JavaScript/uglify.js"))

      // Inlined JS, but mostly code
      assert.ok(!helper.isGenerated("JavaScript/json2_backbone.js"))

      // Minified JS
      assert.ok(!helper.isGenerated("JavaScript/jquery-1.6.1.js"))

      // Go lockfiles
      assert.ok(helper.isGenerated("TOML/filenames/Gopkg.lock"))
      assert.ok(helper.isGenerated("YAML/filenames/glide.lock"))

      // Cargo generated Cargo.lock file
      assert.ok(helper.isGenerated("TOML/filenames/Cargo.lock"))

      // Composer generated composer.lock file
      assert.ok(helper.isGenerated("JSON/filenames/composer.lock"))

      // Generated PostScript
      assert.ok(!helper.isGenerated("PostScript/sierpinski.ps"))

      // These examples are too basic to tell
      assert.ok(!helper.isGenerated("JavaScript/hello.js"))

      assert.ok(!helper.isGenerated("JavaScript/intro-old.js"))
      assert.ok(!helper.isGenerated("JavaScript/classes-old.js"))

      assert.ok(!helper.isGenerated("JavaScript/intro.js"))
      assert.ok(!helper.isGenerated("JavaScript/classes.js"))

      assert.ok(helper.isGenerated("JavaScript/ccalc-lex.js"))
      assert.ok(helper.isGenerated("JavaScript/ccalc-parse.js"))

      // Protocol Buffer generated code
      assert.ok(helper.isGenerated("C++/protocol-buffer.pb.h"))
      assert.ok(helper.isGenerated("C++/protocol-buffer.pb.cc"))
      assert.ok(helper.isGenerated("Java/ProtocolBuffer.java"))
      assert.ok(helper.isGenerated("Python/protocol_buffer_pb2.py"))
      assert.ok(helper.isGenerated("Go/api.pb.go"))
      assert.ok(helper.isGenerated("Go/embedded.go"))
      assert.ok(helper.isGenerated("JavaScript/proto.js"))

      // Generated JNI
      assert.ok(helper.isGenerated("C/jni_layer.h"))

      // Minified CSS
      assert.ok(!helper.isGenerated("CSS/bootstrap.css"))
      assert.ok(helper.isGenerated("CSS/bootstrap.min.css"))

      // Generated VCR
      assert.ok(helper.isGenerated("YAML/vcr_cassette.yml"))

      // Generated by Zephir
      assert.ok(!helper.isGenerated("Zephir/Router.zep"))

      // Go vendored dependencies
      assert.ok(!helper.isGenerated("vendor/vendor.json"))
      assert.ok(helper.isGenerated("vendor/github.com/kr/s3/sign.go"))
      assert.ok(!helper.isGenerated("go/food_vendor/candy.go"))

      // Cython-generated C/C++
      assert.ok(helper.isGenerated("C/sgd_fast.c"))
      assert.ok(helper.isGenerated("C++/wrapper_inner.cpp"))

      // Unity3D-generated metadata
      assert.ok(helper.isGenerated("Unity3D Asset/Tiles.meta"))

      // Racc-generated Ruby
      assert.ok(helper.isGenerated("Ruby/racc.rb"))

      // protobuf/grpc-plugin C++
      assert.ok(helper.isGenerated("C++/hello.grpc.pb.h"))
      assert.ok(helper.isGenerated("C++/grpc.pb.cc"))

      // pkgdown-generateed HTML
      assert.ok(helper.isGenerated("HTML/pkgdown.html"))
    });
  });
});

