name: Run Tests

on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Create SBOM
        uses: anchore/sbom-action@v0
        with:
          image: kimb88/hello-world-spring-boot
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
      - name: Xeol End-of-Life (EOL) Scan
        uses: xeol-io/xeol-action@v1.0.7
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
            
